jenkinsdata:
 build: jenkins-data
jenkinsslave:
 build: jenkins-slave
 volumes_from:
  - jenkinsdata
 volumes:
  - /var/run/docker.sock:/var/run/docker.sock
jenkinsmaster:
 build: jenkins-master
 volumes_from:
  - jenkinsdata
 ports:
  - "40000:40000"
  - "49001:8080"
 links:
  - jenkinsslave:jenkins-slave
jenkinsnginx:
 build: jenkins-nginx
 ports:
  - "80:80"
 links:
  - jenkinsmaster:jenkins-master
